### ISSUE TITLE
Try to fix playx support.

### ISSUE THREAD

**Issue by MDFL64** [lunation/Awesomium-Killer-2.0#26]

**Comment by Cynosphere** [comment]
Media Player also affected

**Comment by MDFL64** [comment]
Will try fixing these issues sometime this week.

**Comment by MDFL64** [comment]
Couldn't get playx working despite fixing issues with external calls and enabling flash.  That being said, it seems to do a pretty good job of breaking itself regardless of whether this is installed.

Media player has some more pressing issues -- It really seems to enjoy crashing.  I'll make it a priority I suppose.

**Comment by MDFL64** [comment]
Interestingly, Zor Player works fine.

**Comment by MDFL64** [comment]
PlayX now mostly works but crashes on deletion.

**Comment by MDFL64** [comment]
Hopefully fixed crash. Seems to paint with large black bars on top/sides. Not sure this is worth worrying about. Will leave issue open just in case.
