### ISSUE TITLE
how to contribute

### ISSUE THREAD

**Issue by Noiwex** [lunation/Awesomium-Killer-2.0#27]
just pull requests?

**Comment by birdbrainswagtrain** [comment]
Yeah.Here's instructions on building, which I'll copy into the readme.

# Contributing
**Warning: Source code is a total shitshow. Code at your own risk.**

**Software**
- VS2015
- CMake

**Instructions**
1. Clone the repo.
2. Run the premake script.
3. Get a CEF build from https://cefbuilds.com/ and put it in the "cef" directory of this repo. I'm currently using build 2704. If you use another build you might have to change the path of the dll wrapper shit. 
4. Run cmake on CEF, this is needed to build the dll wrapper. Disable 
5. Open up the CEF solution and do a release build.
6. Should be ready to build the module. The solution can be found in the "project" directory of the repo.

**Configurations**
Test - Enables logging, copies output to garrysmod directory, which you may need to change on your machine.
Release - Enables optimizations. Copies to the "release" directory in the repo.

**Project Setup**
I recommend that you read about CEF's architecture if you want to contribute, as it is a bit complex: https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-important-concepts

The project consists of two parts: The replacement for the awesomium module, and the subprocess executable. The module (and garrysmod, by extension) act as the "main" process, while the subprocess is used for rendering and javascript shenanigans.

**Comment by Noiwex** [comment]
4. Run cmake on CEF, this is needed to build the dll wrapper. Disable 

what

**Comment by birdbrainswagtrain** [comment]
Fixed.
