### ISSUE TITLE
In-game lua editor/clientside lua viewer crash

### ISSUE THREAD

**Issue by Cynosphere** [lunation/Awesomium-Killer-2.0#33]
Lua editor Metastruct and Clientside Lua Viewer use crash the game

**Comment by Cynosphere** [comment]
If you need a test sample: https://github.com/glua/clientside-lua-viewer/tree/master/lua/menu_plugins/luaviewer

**Comment by MDFL64** [comment]
Alright, this should be useful in figuring out where all the damn crashes are coming from.

**Comment by Cynosphere** [comment]
Any update on this at all?

**Comment by MDFL64** [comment]
Finally bothered to enable debugging symbols and I've figured out where one of the crashes is coming from. Hopefully I can get a more stable release out soon.

**Comment by MDFL64** [comment]
This particular crash seems to be caused by an issue with the incomplete JSON parsing. Should be an easy fix. Note that I've only tested with the metastruct editor, not the client lua viewer as I didn't want to install it.
