### ISSUE TITLE
Crash when rapidly selecting text or dragging selection (IDK)

### ISSUE THREAD

**Issue by PeteSavarese** [lunation/Awesomium-Killer-2.0#34]
Seems that it takes longer for some text to show up, and rapidly selecting text (Or maybe just selecting and dragging the selection, idk) crashes gmod.

https://www.youtube.com/watch?v=0dRyfM_Tesc

**Comment by MDFL64** [comment]
Come to think of it, it is entirely possible that click-dragging is fucked. I'll see what I can do about this soon!

**Comment by MDFL64** [comment]
Should be fixed in the next version.
